### ISSUE TITLE
Reporter crashes when root-level before hook encounters an error

### ISSUE THREAD

**Issue by kmendoza-bt** [alecmestroni/cypress-xray-junit-reporter#5]
Given this sample code
```
before(function() {
    cy.visit('https://example.com')
    cy.get('non-existent-element').should('exist')
})

beforeEach(function() {
    cy.visit('https://example.com')
    cy.get('non-existent-element').should('be.visible')
})

describe('A Test', () => {
    it('Test', { jiraKey: "EPM-00000" }, function()
    {
        expect(1).to.be.eq(1)
    })

    it('Other Test', { jiraKey: "EPM-00000" }, function()
    {
        expect(1).to.be.eq(-10)
    })
})
```

The before hook will fail. When cypress-xray-junit-reporter generates the report the following exception is thrown
```
Suite counting error: suite title not corresponding.
Expect: A Test, got: undefined
Error: Suite counting error: suite title not corresponding.
Expect: A Test, got: undefined
    at findSuite (/<redacted>/node_modules/cypress-xray-junit-reporter/index.js:180:15)
    at /<redacted>/node_modules/cypress-xray-junit-reporter/index.js:202:11
    at Array.forEach (<anonymous>)
    at processTests (/<redacted>/node_modules/cypress-xray-junit-reporter/index.js:192:11)
    at /<redacted>/node_modules/cypress-xray-junit-reporter/index.js:235:9
    at Array.forEach (<anonymous>)
    at processSuites (/<redacted>/node_modules/cypress-xray-junit-reporter/index.js:227:12)
    at CypressXrayJunitReporter.<anonymous> (/<redacted>/node_modules/cypress-xray-junit-reporter/index.js:308:5)
    at L.emit (node:events:526:35)
    at A.emit (<embedded>:2977:18259)
    at Object.onMocha (<embedded>:3030:28781)
    at p.<anonymous> (<embedded>:2977:40309)
    at p.emit (node:events:514:28)
    at <embedded>:2977:26630
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

This issue was identified on version 1.1.10.

**Comment by alecmestroni** [comment]
Try with the hooks inside the describe, for me is working 
```
describe('A Test', () => {
  before(function () {
    cy.visit('https://example.com')
    cy.get('non-existent-element').should('exist')
  })

  beforeEach(function () {
    cy.visit('https://example.com')
    cy.get('non-existent-element').should('be.visible')
  })
  it('Test', { jiraKey: "EPM-00000" }, function () {
    expect(1).to.be.eq(1)
  })

  it('Other Test', { jiraKey: "EPM-00000" }, function () {
    expect(1).to.be.eq(-10)
  })
})
```

Meanwhile I try to fix the issue setting the hook outside the describe
